Improve automatic release deployment

diff --git a/.github/actions/bump-maven-version/action.yml b/.github/actions/bump-maven-version/action.yml
--- a/.github/actions/bump-maven-version/action.yml
+++ b/.github/actions/bump-maven-version/action.yml
@@ -20,21 +20,38 @@ runs:
         # Get current version
         CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
         # Get the latest version bump commit message
-        EXISTING_BUMP=$(git log --grep="Release new patch version ${CURRENT_VERSION}" --pretty=format:"%s")
-        
-        if [[ "$EXISTING_BUMP" == "Release new patch version ${CURRENT_VERSION}" ]]; then
+        EXISTING_BUMP_COUNT=$(git log --grep="Release .* ${CURRENT_VERSION}" --pretty=format:"%s" | wc -l)
+          
+        if [[ "$EXISTING_BUMP_COUNT" -gt 0 ]]; then
           echo "The version ${CURRENT_VERSION} has already been bumped."
           echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
           echo "was_bumped=false" >> $GITHUB_OUTPUT
           exit 0
         fi
         
+        echo "Going to bump ${{ inputs.bump }} version from ${CURRENT_VERSION}."
+        
         # Break down the version number into its components
         IFS='.-' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
+        
+        # Check if the version was correctly broken down into parts
+        if [[ "${#VERSION_PARTS[@]}" -lt 3 ]]; then
+          echo "Error: Unable to parse version number ${CURRENT_VERSION}"
+          exit 1
+        fi
         
         MAJOR=${VERSION_PARTS[0]}
         MINOR=${VERSION_PARTS[1]}
         PATCH=${VERSION_PARTS[2]}
+        IS_SNAPSHOT=${VERSION_PARTS[3]}
+        
+        if [[ -z "$IS_SNAPSHOT" && "${{ inputs.bump }}" != 'snapshot' ]]; then
+          echo "The version ${CURRENT_VERSION} is not snapshot, so it can be bumped only with snapshot bump."
+          echo "We suppose there was error in previous run of workflow, therefore we do not bump here, so the process can continue idempotently."
+          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
+          echo "was_bumped=false" >> $GITHUB_OUTPUT
+          exit 0
+        fi
         
         SNAPSHOT=""
         
@@ -62,6 +79,7 @@ runs:
         
         NEW_VERSION="$MAJOR.$MINOR.$PATCH$SNAPSHOT"
 
+        echo "bumped version is: ${NEW_VERSION}."
         # Set the new version in the POM files
         mvn versions:set -DnewVersion=$NEW_VERSION
 
